[package]
name = "rogue-rust"
version = "0.1.0"
authors = ["Chris Atkin <atkinchris@gmail.com>"]
publish = true

[dependencies]
tcod = { version = "0.13.0", features = ["serialization"] }
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
