[package]
name = "rogue-rust"
version = "0.1.0"
authors = ["Chris Atkin <atkinchris@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.6", features = ["serde"] }

[dependencies.amethyst]
version = "0.11"
features = ["metal"]
